import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Home from "./components/Home";
import SocialMedia from "./components/SocialMedia"
import FallingParticles from "./components/FallingParticles"
import Team from "./components/team";
import ContactUs from "./components/SocialMedia";
import Events from './components/Events';
import AboutUs from "./components/AboutUs";
import Footer from "./components/footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "GDG WEBSITE VIIT25",
  description: "Generated by create next app",
   icons: {
    icon: "/gdgfavi.jpg", 
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        <Home/>
        <FallingParticles/>
        <AboutUs/>
        <Events/>
        <Team/>
        <ContactUs/>
        <Footer/>
        {children}
      </body>
    </html>
  );
}
